// <auto-generated />
using System;
using KDS.Api.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KDS.Api.Migrations
{
    [DbContext(typeof(DataModel))]
    [Migration("20180717211107_kdsMigrations")]
    partial class kdsMigrations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846");

            modelBuilder.Entity("KDS.Api.Models.Comanda", b =>
                {
                    b.Property<long>("idComanda")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("dataHoraInclusao");

                    b.Property<string>("numeroComanda")
                        .HasMaxLength(50);

                    b.HasKey("idComanda");

                    b.ToTable("Comanda");
                });

            modelBuilder.Entity("KDS.Api.Models.Historico", b =>
                {
                    b.Property<long>("idHistorico")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("dataHora");

                    b.Property<int>("id");

                    b.Property<int>("idStatus");

                    b.Property<string>("tipo")
                        .HasMaxLength(50);

                    b.HasKey("idHistorico");

                    b.ToTable("Historico");
                });

            modelBuilder.Entity("KDS.Api.Models.Item", b =>
                {
                    b.Property<long>("idItem")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("PedidoidPedido");

                    b.Property<int>("codigoStatusAtualItem");

                    b.Property<DateTime>("dataHoraInclusao");

                    b.Property<string>("descricao")
                        .HasMaxLength(150);

                    b.Property<int>("idPedido");

                    b.Property<string>("objectId")
                        .HasMaxLength(50);

                    b.Property<string>("observacao")
                        .HasMaxLength(150);

                    b.Property<string>("statusAtualItem")
                        .HasMaxLength(50);

                    b.Property<int>("tempoMedioPreparacaoEmMinutos");

                    b.HasKey("idItem");

                    b.HasIndex("PedidoidPedido");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("KDS.Api.Models.ItemAdicional", b =>
                {
                    b.Property<long>("idAdicional")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("ItemidItem");

                    b.Property<string>("descricao")
                        .HasMaxLength(150);

                    b.Property<int>("idItem");

                    b.HasKey("idAdicional");

                    b.HasIndex("ItemidItem");

                    b.ToTable("ItemAdicional");
                });

            modelBuilder.Entity("KDS.Api.Models.ItemInsumo", b =>
                {
                    b.Property<long>("idInsumo")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("ItemidItem");

                    b.Property<string>("descricao")
                        .HasMaxLength(250);

                    b.Property<int>("idItem");

                    b.Property<string>("objectId")
                        .HasMaxLength(50);

                    b.Property<int>("quantidade");

                    b.Property<int>("remover");

                    b.HasKey("idInsumo");

                    b.HasIndex("ItemidItem");

                    b.ToTable("ItemInsumo");
                });

            modelBuilder.Entity("KDS.Api.Models.Pedido", b =>
                {
                    b.Property<long>("idPedido")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("ComandaidComanda");

                    b.Property<string>("canalAtendimento")
                        .HasMaxLength(50);

                    b.Property<int>("codigoPedido");

                    b.Property<int>("codigoStatusAtualPedido");

                    b.Property<DateTime>("dataHoraInclusao");

                    b.Property<int>("idComanda");

                    b.Property<string>("statusAtualPedido")
                        .HasMaxLength(50);

                    b.HasKey("idPedido");

                    b.HasIndex("ComandaidComanda");

                    b.ToTable("Pedido");
                });

            modelBuilder.Entity("KDS.Api.Models.Status", b =>
                {
                    b.Property<long>("idStatus")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("descricao")
                        .HasMaxLength(50);

                    b.HasKey("idStatus");

                    b.ToTable("Status");
                });

            modelBuilder.Entity("KDS.Api.Models.Item", b =>
                {
                    b.HasOne("KDS.Api.Models.Pedido")
                        .WithMany("itensDoPedido")
                        .HasForeignKey("PedidoidPedido");
                });

            modelBuilder.Entity("KDS.Api.Models.ItemAdicional", b =>
                {
                    b.HasOne("KDS.Api.Models.Item")
                        .WithMany("adicionaisItem")
                        .HasForeignKey("ItemidItem");
                });

            modelBuilder.Entity("KDS.Api.Models.ItemInsumo", b =>
                {
                    b.HasOne("KDS.Api.Models.Item")
                        .WithMany("insumoItem")
                        .HasForeignKey("ItemidItem");
                });

            modelBuilder.Entity("KDS.Api.Models.Pedido", b =>
                {
                    b.HasOne("KDS.Api.Models.Comanda")
                        .WithMany("pedidos")
                        .HasForeignKey("ComandaidComanda");
                });
#pragma warning restore 612, 618
        }
    }
}
