USE [master]
GO

/****** Object:  Database [KDSlocal]    Script Date: 27/06/2018 11:02:08 ******/
CREATE DATABASE [KDSlocal]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'KDSlocal', FILENAME = N'C:\SQLQA\DATA\KDSlocal.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'KDSlocal_log', FILENAME = N'C:\SQLQA\DATA\KDSlocal_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [KDSlocal] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [KDSlocal].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [KDSlocal] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [KDSlocal] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [KDSlocal] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [KDSlocal] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [KDSlocal] SET ARITHABORT OFF 
GO

ALTER DATABASE [KDSlocal] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [KDSlocal] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [KDSlocal] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [KDSlocal] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [KDSlocal] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [KDSlocal] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [KDSlocal] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [KDSlocal] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [KDSlocal] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [KDSlocal] SET  DISABLE_BROKER 
GO

ALTER DATABASE [KDSlocal] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [KDSlocal] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [KDSlocal] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [KDSlocal] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [KDSlocal] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [KDSlocal] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [KDSlocal] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [KDSlocal] SET RECOVERY FULL 
GO

ALTER DATABASE [KDSlocal] SET  MULTI_USER 
GO

ALTER DATABASE [KDSlocal] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [KDSlocal] SET DB_CHAINING OFF 
GO

ALTER DATABASE [KDSlocal] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [KDSlocal] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [KDSlocal] SET  READ_WRITE 
GO


