USE [master]
GO

/****** Object:  Database [KDS]    Script Date: 27/06/2018 11:02:08 ******/
CREATE DATABASE [KDS]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'KDS', FILENAME = N'F:\SQLQA\DATA\KDS.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'KDS_log', FILENAME = N'F:\SQLQA\DATA\KDS_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [KDS] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [KDS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [KDS] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [KDS] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [KDS] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [KDS] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [KDS] SET ARITHABORT OFF 
GO

ALTER DATABASE [KDS] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [KDS] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [KDS] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [KDS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [KDS] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [KDS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [KDS] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [KDS] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [KDS] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [KDS] SET  DISABLE_BROKER 
GO

ALTER DATABASE [KDS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [KDS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [KDS] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [KDS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [KDS] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [KDS] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [KDS] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [KDS] SET RECOVERY FULL 
GO

ALTER DATABASE [KDS] SET  MULTI_USER 
GO

ALTER DATABASE [KDS] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [KDS] SET DB_CHAINING OFF 
GO

ALTER DATABASE [KDS] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [KDS] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [KDS] SET  READ_WRITE 
GO


